### PR TITLE
Detect number of processors for parallel runs

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

### CODE REVIEW

**Comment by mithro** [comment]
```
========================================
Host CPU
----------------------------------------
Cores: 16

Memory
----------------------------------------
MemTotal:       107263700 kB
MemFree:        105102220 kB
MemAvailable:   106097176 kB
Buffers:           91864 kB
Cached:          1457936 kB
SwapCached:            0 kB
Active:          1021060 kB
Inactive:         616064 kB
Active(anon):      87588 kB
Inactive(anon):     8512 kB
Active(file):     933472 kB
Inactive(file):   607552 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1048572 kB
SwapFree:        1048572 kB
Dirty:             55504 kB
Writeback:             0 kB
AnonPages:         86920 kB
Mapped:            84792 kB
Shmem:              8772 kB
Slab:             161868 kB
SReclaimable:     125372 kB
SUnreclaim:        36496 kB
KernelStack:        5568 kB
PageTables:         4080 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    54680420 kB
Committed_AS:     734712 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     28672 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       83952 kB
DirectMap2M:     4110336 kB
DirectMap1G:    106954752 kB
----------------------------------------
Total Memory (GB): 102
Simultaneous runs (16 GB each): 6
Max cores: 6
```

**Comment by mithro** [comment]
@alaindargelas - It's still not using `-j` in the compiling step, we should add it there too.

**Comment by mithro** [comment]
Looks like the whole build run in 21 minutes 18 seconds.

However, it seems to be running the tests very quickly?
`mkdir -p build/tests; cd build; rm -rf test; mkdir test; cd test; ../../tests/cmake_gen.tcl; cmake .; make -j 16; cd ..; ../tests/regression.tcl diff_mode show_diff;`
`Skipping large tests`

`Starts on 05/02/2020 20:38:56`
`---End on 05/02/2020 20:39:08`
That seems too fast?

**Comment by alaindargelas** [comment]
That's fake, that is the time it took the post-process tcl script to
analyze all the tests once they ran (parse all the log files in one single
thread : 10s).
The actual tests run in about 3 minutes with my 24 CPUs at home. Should be
around 4 mins with 16 CPUs. I'll add a time command in the Makefile to see
the actual time.

**Comment by mithro** [comment]
I sounds like we should be able to get the CI time under 10m then?

**Comment by alaindargelas** [comment]
Once the build is parallel yes.It looks like the unit test build is happening serially. I'll let Rafal figure this out. He set it up.

Sent from Yahoo Mail on Android 
 
  On Sat, May 2, 2020 at 21:15, Tim Ansell<notifications@github.com> wrote:   


I sounds like we should be able to get the CI time under 10m then?

**Pull request merged**
