### PR TITLE
Issue #1019: Swap resident copy of antlr4 with fork

### PR DESCRIPTION
**Pull request by hs-apotell**
Issue #1019
A modified version of antlr4 is used without forking.

Resolution:
Forked original antlr4 and applied the necessary changes on top of it.
In the process, upgraded to use antlr4 v4.9.1
Antlr4 is now a submodule.

### CODE REVIEW

**Comment by mithro** [comment]
FYI - @hzeller

**Comment by hzeller** [comment]
For the fork, I'd suggest to have a separate 'surelog' or 'improvements'-branch in the https://github.com/hs-apotell/antlr4 repository, so that we have a master that just tracks upstream, and the branch that contains all the improvements. It makes it much simpler after a while to see what these changes are, otherwise they get intermingled over time and it also makes it much harder to later update the upstream tracking.

Other than that, I like the idea of antlr being a submodule.

**Comment by hzeller** [comment]
(having a separate branch also makes it easier to create a pull request from there upstream)

**Comment by alaindargelas** [comment]
Do you want to make the modif above before I merge?

**Comment by hs-apotell** [comment]
> I'd suggest to have a separate 'surelog' or 'improvements'-branch

Created a new branch named "Surelog" and updated the Surelog/.gitmodules to pull this specific branch.

> Where is the preserved customized version? And how to we make it the default?

All customization are in https://github.com/hs-apotell/antlr4.git repository in branch named "Surelog". Once this PR is merged that will become the default because of the change in Surelog/.gitmodules file.

> Can you point me the files where this is happening?

Look for the change to Surelog/.gitmodules file in this PR

@alaindargelas The antlr4 repository is currently under my personal account. Post this PR merge I will transfer the repository to you. Once you accept the transfer, you can update the Surelog/.gitmodules file to point it to the new address.

**Comment by alaindargelas** [comment]
@hs-apotell, please note this changelist brings hundreds of warnings like the following:

antlr4/runtime/Cpp/runtime/src/atn/ATNState.h:73:26: warning: type attributes ignored after type is already defined [-Wattributes]
   class ANTLR4CPP_PUBLIC ATN;
                          ^~~
In file included from /home/alain/Surelog/third_party/antlr4/runtime/Cpp/runtime/src/atn/PredictionContext.h:10:0,
                 from /home/alain/Surelog/third_party/antlr4/runtime/Cpp/runtime/src/LexerInterpreter.h:9,
                 from /home/alain/Surelog/third_party/antlr4/runtime/Cpp/runtime/src/antlr4-runtime.h:32,
                 from /home/alain/Surelog/src/parser/SV3_1aPpLexer.h:7,
                 from /home/alain/Surelog/src/SourceCompile/PreprocessFile.h:32,
                 from /home/alain/Surelog/src/DesignCompile/CompileStmt.cpp:32:

**Comment by hs-apotell** [comment]
@alaindargelas Warnings fixed #1034 

Also, I am unable to transfer the ownership of the repository to you. I keep getting this error -

```You don’t have the permission to create public repositories on alainmarcel ```

**Comment by alaindargelas** [comment]
Let me add you to the list of authorized contributors.

    On Thursday, January 21, 2021, 02:43:41 AM HAST, HS <notifications@github.com> wrote:  
 
 


@alaindargelas Warnings fixed #1034

Also, I am unable to transfer the ownership of the repository to you. I keep getting this error -

You don’t have the permission to create public repositories on alainmarcel

**Comment by alaindargelas** [comment]
Let me know if you can after accepting the Github invite.

**Comment by hs-apotell** [comment]
@alaindargelas That worked. You should have received an invitation to accept the transfer request. Once accepted, you can update the .gitmodule to point to the new address.

**Comment by alaindargelas** [comment]
Thanks.
Expect a few more days before I integrate this. I'm in the middle of a
major Elaboration change, I don't want lose track of it.

**Pull request merged**
