### PR TITLE
CI: add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by umarcor**
Close #846

As discussed in #631, this PR adds a GitHub Actions workflow for building and testing on Ubuntu.

### CODE REVIEW

**Comment by alaindargelas** [comment]
@umarcor Why did you delete the .travis file?

**Comment by umarcor** [comment]
@alaindargelas the GitHub workflow is equivalent to the `.travis.yml` file. The timout in Travis is 50min, while in GHA it's 6h. Moreover, integration of  GHA is better, since each job is shown as a separate test in PRs.

**Comment by alaindargelas** [comment]
@umarcor I wish this was explained before removing the file.
I have not seen the GHA results.
Can you point to the page that shows the builds status?

**Comment by umarcor** [comment]
Sorry about that. As I was pinged because I helped migrating other repos from Travis to GHA, I assumed that was the intent here too.

You can see all the GHA runs in https://github.com/alainmarcel/Surelog/actions. You can also see the runs for each specific commit in https://github.com/alainmarcel/Surelog/commits/master. In PRs, CI results are shown at the bottom. For example: https://github.com/alainmarcel/Surelog/pull/847.

**Comment by alaindargelas** [comment]
OK, thanks!Now I understand.I'll remove the .travis.yml
    On Sunday, October 18, 2020, 09:13:57 PM PDT, umarcor <notifications@github.com> wrote:  
 
 


Sorry about that. As I was pinged because I helped migrating other repos from Travis to GHA, I assumed that was the intent here too.

You can see all the GHA runs in https://github.com/alainmarcel/Surelog/actions. You can also see the runs for each specific commit in https://github.com/alainmarcel/Surelog/commits/master. In PRs, CI results are shown at the bottom. For example: #847.

**Pull request merged**
