### PR TITLE
DO NOT MERGE - TESTING!

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

### CODE REVIEW

**Comment by mithro** [comment]
It is unclear to me why the Windows builder succeeded in doing nothing?

**Comment by mithro** [comment]
The Mac builder failed with;
```
========================================
Host adding PPAs
----------------------------------------
sudo: apt-add-repository: command not found
```
as expected....

**Comment by mithro** [comment]
FYI -- @hzeller

**Comment by hzeller** [comment]
The Mac builder is enabled for all Surelog tests, essentially rendering all recent commits as 'failed'; we learned to ignore that, but that is not really something we should train us to do :)

Is there a way to disable the Mac build until it is working @mithro ?

**Comment by mithro** [comment]
@hzeller - I have disabled the Mac Kokoro.

**Comment by mithro** [comment]
@hzeller

**Pull request closed without merging**
