### PR TITLE
First step towards const correctness. Code improvement, no change in …

### PR DESCRIPTION
**Pull request by hzeller**
…functionality.

Mostly starting with FileContent, making a bunch of getters const,
add getters calld mutableFoo() if they return a modifyiable value.

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Sorry for the large patch, but const correctness is one of these things where you pull a little thread on one end and end up pulling and pulling until it starts compiling again :)

**Comment by alaindargelas** [comment]
I'll delay merging all these pull request. 
I have a higher priority large change list. I'll let you merge the potential conflicts later.

**Comment by hzeller** [comment]
sounds good to me.

**Comment by alaindargelas** [comment]
As expected, this changelist conflicts with my changes.

**Comment by hzeller** [comment]
Alright, will fix these later today.

**Comment by alaindargelas** [comment]
It is correct, I already updated the logs

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 4, 2020 at 10:31, Henner Zeller<notifications@github.com> wrote:   


Alright, will fix these later today.

**Comment by alaindargelas** [comment]
Replied to wrong thread. I was referring to the deep clone.

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 4, 2020 at 10:31, Henner Zeller<notifications@github.com> wrote:   


Alright, will fix these later today.

**Comment by hzeller** [comment]
(closing this one, and re-opening a separate pull request with fixed merges)

**Pull request closed without merging**
